### ISSUE TITLE
Erreur fatale en PHP8 quand on actualise un flux manuellement dans la liste

### ISSUE THREAD

**Issue by franck-tomek** [JcDenis/zoneclearFeedServer#1]
`Backend fatal error: PHP Fatal error:  Uncaught TypeError: dt::setTZ(): Argument #1 ($tz) must be of type string, null given, called in /planetDC/dotclear/inc/admin/lib.dc.notices.php on line 119 and defined in /planetDC/dotclear/inc/libs/clearbricks/common/lib.date.php:113
Stack trace:
#0 /planetDC/dotclear/inc/admin/lib.dc.notices.php(119): dt::setTZ()
#1 /planetDC/dotclear/inc/admin/lib.dc.notices.php(127): dcAdminNotices::{closure}()
#2 /planetDC/dotclear/inc/admin/lib.dc.page.php(298): dcAdminNotices::addNotice()
#3 /planetDC/dotclear/inc/admin/lib.dc.page.php(303): dcPage::addNotice()
#4 /planetDC/all-blogs/plugins/zoneclearFeedServer/inc/class.zcfs.feedsactions.php(237): dcPage::addSuccessNotice()
#5 /planetDC/dotclear/inc/admin/actions/class.dcaction.php(331): zcfsDefaultFeedsActions::doUpdateFeed()
#6 /planetDC/all-blogs/plugins/zoneclearFeedServer/index.php(481): dcActionsPage->process()
#7 /planetDC/dotclear/admin/plugin.php(43): include('/home/lafr3189/...')
#8 {main}
thrown in /planetDC/dotclear/inc/libs/clearbricks/common/lib.date.php on line 113`

**Comment by JcDenis** [comment]
Normalement résolu à partir de la 2022.11.20 pour dotclear 2.24
